//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.06 at 10:52:12 PM IST 
//


package soap.com.app.producing_web_service;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the soap.com.app.producing_web_service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetAllCustomerRequest_QNAME = new QName("http://com.soap/app/producing-web-service", "getAllCustomerRequest");
    private final static QName _GetAllItemRequest_QNAME = new QName("http://com.soap/app/producing-web-service", "getAllItemRequest");
    private final static QName _GetAllAddressRequest_QNAME = new QName("http://com.soap/app/producing-web-service", "getAllAddressRequest");
    private final static QName _GetAllSaleOrderRequest_QNAME = new QName("http://com.soap/app/producing-web-service", "getAllSaleOrderRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: soap.com.app.producing_web_service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetCustomerResponse }
     * 
     */
    public GetCustomerResponse createGetCustomerResponse() {
        return new GetCustomerResponse();
    }

    /**
     * Create an instance of {@link Customer }
     * 
     */
    public Customer createCustomer() {
        return new Customer();
    }

    /**
     * Create an instance of {@link UpdateAddressRequest }
     * 
     */
    public UpdateAddressRequest createUpdateAddressRequest() {
        return new UpdateAddressRequest();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link GetAddressRequest }
     * 
     */
    public GetAddressRequest createGetAddressRequest() {
        return new GetAddressRequest();
    }

    /**
     * Create an instance of {@link RemoveItemResponse }
     * 
     */
    public RemoveItemResponse createRemoveItemResponse() {
        return new RemoveItemResponse();
    }

    /**
     * Create an instance of {@link AddCustomerResponse }
     * 
     */
    public AddCustomerResponse createAddCustomerResponse() {
        return new AddCustomerResponse();
    }

    /**
     * Create an instance of {@link AddCustomerRequest }
     * 
     */
    public AddCustomerRequest createAddCustomerRequest() {
        return new AddCustomerRequest();
    }

    /**
     * Create an instance of {@link GetSaleOrderResponse }
     * 
     */
    public GetSaleOrderResponse createGetSaleOrderResponse() {
        return new GetSaleOrderResponse();
    }

    /**
     * Create an instance of {@link SaleOrder }
     * 
     */
    public SaleOrder createSaleOrder() {
        return new SaleOrder();
    }

    /**
     * Create an instance of {@link RemoveSaleOrderResponse }
     * 
     */
    public RemoveSaleOrderResponse createRemoveSaleOrderResponse() {
        return new RemoveSaleOrderResponse();
    }

    /**
     * Create an instance of {@link RemoveCustomerRequest }
     * 
     */
    public RemoveCustomerRequest createRemoveCustomerRequest() {
        return new RemoveCustomerRequest();
    }

    /**
     * Create an instance of {@link UpdateSaleOrderResponse }
     * 
     */
    public UpdateSaleOrderResponse createUpdateSaleOrderResponse() {
        return new UpdateSaleOrderResponse();
    }

    /**
     * Create an instance of {@link AddAddressRequest }
     * 
     */
    public AddAddressRequest createAddAddressRequest() {
        return new AddAddressRequest();
    }

    /**
     * Create an instance of {@link GetSaleOrderRequest }
     * 
     */
    public GetSaleOrderRequest createGetSaleOrderRequest() {
        return new GetSaleOrderRequest();
    }

    /**
     * Create an instance of {@link GetItemRequest }
     * 
     */
    public GetItemRequest createGetItemRequest() {
        return new GetItemRequest();
    }

    /**
     * Create an instance of {@link AddItemRequest }
     * 
     */
    public AddItemRequest createAddItemRequest() {
        return new AddItemRequest();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link AddItemResponse }
     * 
     */
    public AddItemResponse createAddItemResponse() {
        return new AddItemResponse();
    }

    /**
     * Create an instance of {@link GetAllCustomerResponse }
     * 
     */
    public GetAllCustomerResponse createGetAllCustomerResponse() {
        return new GetAllCustomerResponse();
    }

    /**
     * Create an instance of {@link UpdateItemResponse }
     * 
     */
    public UpdateItemResponse createUpdateItemResponse() {
        return new UpdateItemResponse();
    }

    /**
     * Create an instance of {@link RemoveAddressRequest }
     * 
     */
    public RemoveAddressRequest createRemoveAddressRequest() {
        return new RemoveAddressRequest();
    }

    /**
     * Create an instance of {@link GetAllSaleOrderResponse }
     * 
     */
    public GetAllSaleOrderResponse createGetAllSaleOrderResponse() {
        return new GetAllSaleOrderResponse();
    }

    /**
     * Create an instance of {@link RemoveSaleOrderRequest }
     * 
     */
    public RemoveSaleOrderRequest createRemoveSaleOrderRequest() {
        return new RemoveSaleOrderRequest();
    }

    /**
     * Create an instance of {@link GetAddressResponse }
     * 
     */
    public GetAddressResponse createGetAddressResponse() {
        return new GetAddressResponse();
    }

    /**
     * Create an instance of {@link GetAllAddressResponse }
     * 
     */
    public GetAllAddressResponse createGetAllAddressResponse() {
        return new GetAllAddressResponse();
    }

    /**
     * Create an instance of {@link GetAllItemResponse }
     * 
     */
    public GetAllItemResponse createGetAllItemResponse() {
        return new GetAllItemResponse();
    }

    /**
     * Create an instance of {@link AddSaleOrderResponse }
     * 
     */
    public AddSaleOrderResponse createAddSaleOrderResponse() {
        return new AddSaleOrderResponse();
    }

    /**
     * Create an instance of {@link RemoveItemRequest }
     * 
     */
    public RemoveItemRequest createRemoveItemRequest() {
        return new RemoveItemRequest();
    }

    /**
     * Create an instance of {@link RemoveCustomerResponse }
     * 
     */
    public RemoveCustomerResponse createRemoveCustomerResponse() {
        return new RemoveCustomerResponse();
    }

    /**
     * Create an instance of {@link AddAddressResponse }
     * 
     */
    public AddAddressResponse createAddAddressResponse() {
        return new AddAddressResponse();
    }

    /**
     * Create an instance of {@link GetCustomerRequest }
     * 
     */
    public GetCustomerRequest createGetCustomerRequest() {
        return new GetCustomerRequest();
    }

    /**
     * Create an instance of {@link GetItemResponse }
     * 
     */
    public GetItemResponse createGetItemResponse() {
        return new GetItemResponse();
    }

    /**
     * Create an instance of {@link UpdateAddressResponse }
     * 
     */
    public UpdateAddressResponse createUpdateAddressResponse() {
        return new UpdateAddressResponse();
    }

    /**
     * Create an instance of {@link RemoveAddressResponse }
     * 
     */
    public RemoveAddressResponse createRemoveAddressResponse() {
        return new RemoveAddressResponse();
    }

    /**
     * Create an instance of {@link UpdateSaleOrderRequest }
     * 
     */
    public UpdateSaleOrderRequest createUpdateSaleOrderRequest() {
        return new UpdateSaleOrderRequest();
    }

    /**
     * Create an instance of {@link AddSaleOrderRequest }
     * 
     */
    public AddSaleOrderRequest createAddSaleOrderRequest() {
        return new AddSaleOrderRequest();
    }

    /**
     * Create an instance of {@link UpdateCustomerRequest }
     * 
     */
    public UpdateCustomerRequest createUpdateCustomerRequest() {
        return new UpdateCustomerRequest();
    }

    /**
     * Create an instance of {@link UpdateCustomerResponse }
     * 
     */
    public UpdateCustomerResponse createUpdateCustomerResponse() {
        return new UpdateCustomerResponse();
    }

    /**
     * Create an instance of {@link UpdateItemRequest }
     * 
     */
    public UpdateItemRequest createUpdateItemRequest() {
        return new UpdateItemRequest();
    }

    /**
     * Create an instance of {@link Void }
     * 
     */
    public Void createVoid() {
        return new Void();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.soap/app/producing-web-service", name = "getAllCustomerRequest")
    public JAXBElement<Object> createGetAllCustomerRequest(Object value) {
        return new JAXBElement<Object>(_GetAllCustomerRequest_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.soap/app/producing-web-service", name = "getAllItemRequest")
    public JAXBElement<Object> createGetAllItemRequest(Object value) {
        return new JAXBElement<Object>(_GetAllItemRequest_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.soap/app/producing-web-service", name = "getAllAddressRequest")
    public JAXBElement<Object> createGetAllAddressRequest(Object value) {
        return new JAXBElement<Object>(_GetAllAddressRequest_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.soap/app/producing-web-service", name = "getAllSaleOrderRequest")
    public JAXBElement<Object> createGetAllSaleOrderRequest(Object value) {
        return new JAXBElement<Object>(_GetAllSaleOrderRequest_QNAME, Object.class, null, value);
    }

}
